### ISSUE TITLE
"Other" category defaults to "personal vehicle"

### ISSUE THREAD

**Issue by omegabytes** [lanebreach/ios_app#18]
When selecting category, a user can take no action and "other" (default field value" will turn into "private vehicle" (selected in menu by default). We should change this so that the displayed category matches the menu item.

Also, remove the flashing cursor from the category field.

**Comment by gumbypp** [comment]
Fixed by moving Other to the top. It's unintuitive to have it change when you open the picker. Done in a5fd34dea2448810b73ae15bd028cf24c9ee37ef.
