### ISSUE TITLE
Switch over from dev to prod 311 report submission

### ISSUE THREAD

**Issue by omegabytes** [lanebreach/ios_app#2]
The app is submitting reports to 311's dev database and will need to be switched over to to the production endpoint.

**Comment by omegabytes** [comment]
@gumbypp could you add some reference documentation here? What is the process?

**Comment by gumbypp** [comment]
Per Carlos Alfonso:

To get a production key:
1. Email me when you are ready for a key
2. I’ll send you list of cases I want you to create in the system
3. Send me an email with the SR#s for the request.
4. I’ll verify and send you a prod key.

**Comment by gumbypp** [comment]
Done in ced1a2a84001662908f79f45a1877f8ebe214afe
