### ISSUE TITLE
reports omit last character

### ISSUE THREAD

**Issue by kemokid** [lanebreach/ios_app#24]
I filed the following three using Lane Breach:

https://twitter.com/EverySF311Bike/status/1138660222321516544
https://twitter.com/EverySF311Bike/status/1138660215124103169
https://twitter.com/EverySF311Bike/status/1138659710528368640

Notice how they're all missing the last letter of the license number? Trust me, I did not fail to enter that last character.

**Comment by gumbypp** [comment]
Thanks for this feedback. I've found and fixed this bug - it will be in the next release.

**Comment by gumbypp** [comment]
Fixed in 4dd2626522d46155b65653e4656675291d2799a2
