### ISSUE TITLE
[Analytics] Add more in-app event tracking to gauge whether users are uploading realtime or batch

### ISSUE THREAD

**Issue by SherlockHomie** [lanebreach/ios_app#27]
We have had several discussions and some user feedback indicating that quickly taking photos with the default camera app and then batch submitting reports at a later time is common use case.

Ultimately we think this is a common use case we need to consider (both for how we design the app, and how our backend / 311 timestamp submissions). Currently 311 timestamps submissions with the time of the submission, not the time of the photo. As a user, if I batch submit reports weekly or even more infrequently, then 311 will be recording stale data as live (and making it increasingly harder to make temporal conclusions about the data submitted).

To keep track of this behavior going forward, and to quickly gather data to support this intuition, lets add the following in-app analytics:
1) Record whether the source of the photo is the live camera, or a photo from the photo gallery
2) In the case that the source of the photo is the photo gallery, record the delta between the current time and the photo's timestamp

With these two pieces of information across a sample of 1-2 weeks or reports, we can better inform our design decisions going forward. Furthermore, we would have some data to backup a API change request to 311 to suggest recording the photo timestamp.

**Comment by gumbypp** [comment]
Done in ca87ef88f50e4ae5935052c119d4bdc70822ae7b
