### ISSUE TITLE
[Onboarding] Usage and safety disclaimer

### ISSUE THREAD

**Issue by SherlockHomie** [lanebreach/ios_app#28]
[Job Story] When I am unsure of how to use the app, I want some guidance on how to use the app while biking, so that I can safely and quickly submit reports when I'm commuting.

Provide the user some guidance on how to use the app (realtime or batch upload later) and a quick safety reminder.

Here is a google drive link to some proposed onboarding text: 
https://docs.google.com/document/d/1WdiDXJyDNAYAteGb7Ojz0-ic2-mwZSYxkzmheJklGIw/edit?usp=sharing

This context would be helpful for first use (onboarding) as well as accessible on demand later.

**Comment by gumbypp** [comment]
@SherlockHomie I suggest adding a mobile-friendly web page to the site which can be accessed from the app's Setting page. How about https://www.lanebreach.org/mobilehelp? Can you do this?

**Comment by gumbypp** [comment]
@omegabytes @SherlockHomie I created a simple mobile help page based on the onboarding google doc. Can we use this until we get the website build pipeline working (and make sure that it still works after the pipeline is up and running)?

https://github.com/lanebreach/lanebreach.github.io/pull/3

**Comment by gumbypp** [comment]
Done in ae11a2ba792048d4167976cb7ebba394855f9244
