### ISSUE TITLE
New vector icon

### ISSUE THREAD

**Issue by kyleconroy** [lanebreach/ios_app#29]
The current icon is [too small](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/#app-icon-sizes) for certain devices. We should also be using the same icon for the App Store.

I recreated the icon in Photoshop using paths so that it can be scaled to any size. Here it is at 1024x1024

![blfa-icon](https://user-images.githubusercontent.com/34893/60041427-3919b380-9670-11e9-9666-45c66dc2a066.png)

I can also include the .psd file, just not sure where you want me to put it.

**Comment by gumbypp** [comment]
Nice icon - thanks!

**Comment by gumbypp** [comment]
Done in 9807296b60d8a621e3a64372ef4408f412c66037
