### ISSUE TITLE
Add legend to map

### ISSUE THREAD

**Issue by omegabytes** [lanebreach/ios_app#4]
Legend should describe:
- bike lane
- report
- injury

**Comment by gumbypp** [comment]
@omegabytes can you provide the icons for each legend item?

**Comment by omegabytes** [comment]
The current legend uses the following colors (but no icons)
- injury/death: #fe0606 
- bike lane: #429d01
- blocked lane: #ffe11f

**Comment by omegabytes** [comment]
If you would like to do icons instead, I propose:
- red dot for injury/death
- green line for bike line
- yellow dot for blockage

I don't really see a value-add for creating icons for MVP though. I would like to hear your thoughts. If adding a legend with dots is the same amount of work as adding a legend with the above (or other icons) please let me know!

**Comment by gumbypp** [comment]
Done in aa1fa93b68170bdbff359e826c33bba4407639a7
